openapi: 3.0.0
servers: [ ]
info:
  description: This is an API for Beetola
  version: "1.0.0"
  title: Simple Currency conversion API
  contact:
    email: romajanlyi141099@gmail
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /currency/sell:
    get:
      summary: conversion endpoint for currency amount
      operationId: convertToSellSome
      description: |
        Calculates what amount of 'to' currency you will get if you sell 'amount' of 'from' currency
      parameters:
        - in: query
          name: from
          description: what currency type do you have
          required: true
          schema:
            type: string
            pattern: '[A-Z]{3}'
        - in: query
          name: to
          description: what currency type you want to get
          required: true
          schema:
            type: string
            pattern: '[A-Z]{3}'
        - in: query
          name: amount
          description: amount to sell money of 'from' currency
          required: true
          schema:
            type: number
            minimum: 1
      responses:
        '200':
          description: conversion response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyConversionRs'
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputRs'
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
  /currency/buy:
    get:
      summary: conversion endpoint for currency amount
      operationId: convertToBuySome
      description: |
        Calculates what amount of 'from' currency you need to buy 'amount' of 'to' currency
      parameters:
        - in: query
          name: from
          description: what currency type do you have
          required: true
          schema:
            type: string
            pattern: '[A-Z]{3}'
        - in: query
          name: to
          description: what currency type you want to get
          required: true
          schema:
            type: string
            pattern: '[A-Z]{3}'
        - in: query
          name: amount
          description: amount of 'to' currency you want to buy
          required: true
          schema:
            type: number
            minimum: 1
      responses:
        '200':
          description: conversion response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyConversionRs'
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputRs'
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
components:
  schemas:
    CurrencyConversionRs:
      type: object
      required:
        - amount
        - commission
      properties:
        amount:
          type: number
        commission:
          type: number
    InvalidInputRs:
      type: object
      description: response for invalid input parameters
#      no reason because it can be insecured
      required:
        - message
      properties:
        message:
          type: string
#         Here can be an error code if you want(for ex. E100(invalid type))
    ServerError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
